//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.DbContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class mst_subjectmarks
    {
        
        public long subject_id { get; set; }
        public long student_id { get; set; }

        [DisplayName("Subject Name")]
        [Required]
        public string subject_name { get; set; }
        
        [DisplayName("Marks")]
        [MaxLength(3)]
        [MinLength(1)]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Please enter proper marks.")]
        [Required]
        public decimal marks { get; set; }
    
        public virtual mst_student mst_student { get; set; }
    }
}
